services:
  web:
    image: tongotherg/django-app:latest
    build: .
    ports:
      - "8000:8000"
    environment:
      - .env

  watchtower:
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower